### ISSUE TITLE
*_properties do not get accepted by ansible

### ISSUE THREAD

**Issue by helt** [azavea/ansible-hdfs#11]
I did set up a small hdfs-cluster for playing. I got it working so far, but no matter what i try, `*_properties` entries will lead to playbook errors. Can you give me a hint whats wrong?

error message is 

```
RUNNING HANDLER [azavea.hdfs : Restart Hadoop HDFS NameNode] *******************
fatal: [odysseus]: FAILED! => {"changed": false, "failed": true, "msg": "stopping namenode\n * Stopped Hadoop namenode: \nstarting namenode, logging to /var/log/hadoop-hdfs/
hadoop-hdfs-namenode-odysseus.out\n * Failed to start Hadoop namenode. Return value: 1\n"}
```

The (probably relevant) expert for the task in the `site.yml` for the master follows. I cropped away the spark stuff...

```
- name: set up cluster master                                        
  hosts: spark-masters                                               
  vars:                                                              
    java_version: "8u77**"                                           
    java_flavor: "oracle"                                            
    java_major_version: "8"                                          
    java_oracle_accept_license_agreement: "True"                     
    hdfs_namenode: "True"                                            
    hdfs_namenode_host: odysseus                                     
#    hdfs_core_properties:                                           
#      - { name: "hadoop.proxyuser.hue.hosts", value: "*" }          # doesnt work
#      - { name: "hadoop.proxyuser.hue.groups", value: "*" }                   # doesnt work either
    hdfs_namenode_properties:                                        
      - { name: "dfs.permissions.enabled", value: "false" }                    # the culprit
#      - { name: "dfs.webhdfs.enabled", value: "true" }                        # same here
  roles:                                                             
    - azavea.java                                                    
    - azavea.hdfs                                                    

  pre_tasks:                                                         
    - name: Update APT cache                                         
      apt: update_cache=yes                                          
```
